{
 "title": "process monitor",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Group",
    "query": {
     "query": "label_values(process_total_cpu_core,job)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(process_cpu_percent{job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(process_cpu_percent{hostname=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(process_cpu_percent{instance=~\"$ip\", name!~\"node_exporter|top\"},name)"
    }
   },
   {
    "name": "command",
    "label": "command",
    "query": {
     "query": "label_values(process_cpu_percent{name!~\"node_exporter|top\", name=~\"$name\", instance=~\"$ip\"},cmd)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total ram",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_total_ram_kb{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "Total ram"
    }
   ]
  },
  {
   "title": "Total Cpu core",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_total_cpu_core{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "Total Cpu core"
    }
   ]
  },
  {
   "title": "Available ram",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_available_ram_kb{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "Available ram"
    }
   ]
  },
  {
   "title": "Free ram",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_free_ram_kb{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "Free ram"
    }
   ]
  },
  {
   "title": "CPU load 1m 5m 15m",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_load_1m{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "process_cpu_load_5m{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "process_cpu_load_15m{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "process_total_cpu_core{hostname=~\"$hostname\",instance=~\"$ip\"}",
     "legendFormat": "Total core"
    }
   ]
  },
  {
   "title": "Process CPU% Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (cmd)(process_cpu_percent{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process MEM% Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (cmd)(process_memory_percent{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cmd)(process_memory_rss_bytes{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cmd)(process_num_fds{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cmd)(process_num_threads{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process I/O write/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(process_io_write_count{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}[1m])) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process I/O read/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(process_io_read_count{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}[1m])) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process I/O read bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(process_io_read_bytes{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}[1m])) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process I/O write bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(process_io_write_bytes{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}[1m])) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process voluntary context switching/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(process_ctx_switches_voluntary{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}[1m])) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process involuntary context switching/s",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(process_ctx_switches_involuntary{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\",cmd=~\"$command\"}[1m])) > 0",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Process info",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_running_seconds{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\"}",
     "legendFormat": "{{cmd}}"
    },
    {
     "expr": "process_cpu_percent{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\"}"
    },
    {
     "expr": "process_memory_rss_bytes{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\"}"
    },
    {
     "expr": "process_memory_percent{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\"}"
    },
    {
     "expr": "process_num_fds{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\"}"
    },
    {
     "expr": "process_num_threads{hostname=~\"$hostname\",instance=~\"$ip\",name=~\"$name\",cmd!~\"top.+\"}"
    },
    {
     "expr": "rate(process_io_read_bytes{hostname=~\"$hostname\", instance=~\"$ip\", name=~\"$name\", cmd!~\"top.+\"}[$__rate_interval])"
    },
    {
     "expr": "rate(process_io_write_bytes{hostname=~\"$hostname\", instance=~\"$ip\", name=~\"$name\", cmd!~\"top.+\"}[$__rate_interval])"
    },
    {
     "expr": "rate(process_io_read_count{hostname=~\"$hostname\", instance=~\"$ip\", name=~\"$name\", cmd!~\"top.+\"}[$__rate_interval])"
    },
    {
     "expr": "rate(process_io_write_count{hostname=~\"$hostname\", instance=~\"$ip\", name=~\"$name\", cmd!~\"top.+\"}[$__rate_interval])"
    },
    {
     "expr": "rate(process_ctx_switches_voluntary{hostname=~\"$hostname\", instance=~\"$ip\", name=~\"$name\", cmd!~\"top.+\"}[$__rate_interval])"
    },
    {
     "expr": "rate(process_ctx_switches_involuntary{hostname=~\"$hostname\", instance=~\"$ip\", name=~\"$name\", cmd!~\"top.+\"}[$__rate_interval])"
    }
   ]
  }
 ]
}